### ISSUE TITLE
installation using ipk does not install /etc/init.d/netclient

### ISSUE THREAD

**Issue by vollkommenheit** [sbilly/netmaker-openwrt#1]
Specifically "opkg install netmaker-dev_0.9.0-1_all-openwrt-19.07.ipk" finishes silently, without indicating success or failure. No /etc/init.d/netclient as expected. There is, however, /usr/share/gocode/src/github.com/gravitl/netmaker/netclient on the file system.

**Comment by sbilly** [comment]
`netmaker-dev_*.ipk` (eg. `netmaker-dev_0.9.0-1_all-openwrt-21.02.ipk`) are source code packages for development, use `netmaker_*.ipk` (eg. `netmaker_0.9.0-1_x86_64-openwrt-21.02.ipk`) instead.
